services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: laravelcp_frontend
    ports:
      - "5175:5175"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev -- --host 0.0.0.0
    networks:
      - laravelcp_net

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravelcp_backend
    ports:
      - "8001:80"
    volumes:
      - ./backend:/srv/laravelcp/backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APACHE_DOCUMENT_ROOT=/srv/laravelcp/backend/public
      - APP_DEBUG=1
    networks:
      - laravelcp_net
    restart: unless-stopped

  scheduler:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravelcp_scheduler
    volumes:
      - ./backend:/srv/laravelcp/backend
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - APP_DEBUG=1
    command: php artisan schedule:work
    networks:
      - laravelcp_net
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: laravelcp_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravelcp
      MYSQL_USER: laravelcp
      MYSQL_PASSWORD: laravelcp
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot" ]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - laravelcp_net
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: laravelcp_pma
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - laravelcp_net
    restart: unless-stopped

volumes:
  mysql_data:


networks:
  laravelcp_net:
    driver: bridge
