#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

$basePath = realpath(__DIR__) ?: __DIR__;

// Register the Composer autoloader...
require $basePath . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once $basePath . '/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);
