<?php

use App\Plugins\SportsBot\Controllers\Admin\SportsBotController;
use Illuminate\Support\Facades\Route;

Route::prefix('sportsbot')->name('sportsbot.')->group(function () {
    Route::get('/status', [SportsBotController::class, 'status'])->name('status');
    Route::get('/autopilot', [SportsBotController::class, 'autopilotStatus'])->name('autopilot');
    Route::get('/post-timings', [SportsBotController::class, 'postTimings'])->name('post-timings');
    Route::post('/post-timings', [SportsBotController::class, 'savePostTimings'])->name('post-timings.save');
    Route::post('/run', [SportsBotController::class, 'run'])->name('run');
    Route::post('/test-route', [SportsBotController::class, 'testRoute'])->name('test-route');
    Route::get('/fixture-queue', [SportsBotController::class, 'fixtureQueue'])->name('fixture-queue');
    Route::post('/fixture-queue/prefetch', [SportsBotController::class, 'fixtureQueuePrefetch'])->name('fixture-queue.prefetch');
    Route::post('/fixture-queue/render', [SportsBotController::class, 'fixtureQueueRender'])->name('fixture-queue.render');
    Route::post('/fixture-queue/publish', [SportsBotController::class, 'fixtureQueuePublish'])->name('fixture-queue.publish');
    Route::get('/fixture-queue/{id}', [SportsBotController::class, 'fixtureQueueItem'])->name('fixture-queue.item');
    Route::post('/fixture-queue/{id}/re-render', [SportsBotController::class, 'fixtureQueueReRender'])->name('fixture-queue.re-render');
    Route::post('/fixture-queue/{id}/publish', [SportsBotController::class, 'fixtureQueuePublishNow'])->name('fixture-queue.publish-now');
    Route::post('/fixture-queue/{id}/find-poster', [SportsBotController::class, 'fixtureQueueFindPoster'])->name('fixture-queue.find-poster');
    Route::post('/fixture-queue/{id}/find-tv-info', [SportsBotController::class, 'fixtureQueueFindTvInfo'])->name('fixture-queue.find-tv-info');
    Route::post('/fixture-queue/{id}/refresh-scraped-data', [SportsBotController::class, 'fixtureQueueRefreshScrapedData'])->name('fixture-queue.refresh-scraped-data');
    Route::post('/fixture-queue/{id}/accept-scraped-data', [SportsBotController::class, 'fixtureQueueAcceptScrapedData'])->name('fixture-queue.accept-scraped-data');
    Route::post('/fixture-queue/{id}/reject-scraped-data', [SportsBotController::class, 'fixtureQueueRejectScrapedData'])->name('fixture-queue.reject-scraped-data');
    Route::post('/fixture-queue/{id}/skip', [SportsBotController::class, 'fixtureQueueSkip'])->name('fixture-queue.skip');
    Route::delete('/fixture-queue/{id}', [SportsBotController::class, 'fixtureQueueDelete'])->name('fixture-queue.delete');
    Route::post('/fixtures-today/preview', [SportsBotController::class, 'fixturesTodayPreview'])->name('fixtures-today.preview');
    Route::post('/fixtures-today/send', [SportsBotController::class, 'fixturesTodaySend'])->name('fixtures-today.send');
    Route::post('/football-fixtures/preview', [SportsBotController::class, 'footballFixturesPreview'])->name('football-fixtures.preview');
    Route::post('/football-fixtures/send', [SportsBotController::class, 'footballFixturesSend'])->name('football-fixtures.send');
    Route::post('/rugby-fixtures/preview', [SportsBotController::class, 'rugbyFixturesPreview'])->name('rugby-fixtures.preview');
    Route::post('/rugby-fixtures/send', [SportsBotController::class, 'rugbyFixturesSend'])->name('rugby-fixtures.send');
    Route::post('/fight-fixtures/preview', [SportsBotController::class, 'fightFixturesPreview'])->name('fight-fixtures.preview');
    Route::post('/fight-fixtures/send', [SportsBotController::class, 'fightFixturesSend'])->name('fight-fixtures.send');
    Route::post('/motorsport-fixtures/preview', [SportsBotController::class, 'motorsportFixturesPreview'])->name('motorsport-fixtures.preview');
    Route::post('/motorsport-fixtures/send', [SportsBotController::class, 'motorsportFixturesSend'])->name('motorsport-fixtures.send');
    Route::post('/fixtures/{sport}/preview', [SportsBotController::class, 'sportFixturePreview'])->name('fixtures.preview');
    Route::post('/fixtures/{sport}/send', [SportsBotController::class, 'sportFixtureSend'])->name('fixtures.send');
    Route::post('/fixtures/{sport}/publish', [SportsBotController::class, 'sportFixturePublish'])->name('fixtures.publish');
    Route::post('/tv-guide/preview', [SportsBotController::class, 'tvGuidePreview'])->name('tv-guide.preview');
    Route::post('/tv-guide/send', [SportsBotController::class, 'tvGuideSend'])->name('tv-guide.send');
    Route::post('/live-now/preview', [SportsBotController::class, 'liveNowPreview'])->name('live-now.preview');
    Route::post('/live-now/send', [SportsBotController::class, 'liveNowSend'])->name('live-now.send');
    Route::get('/coverage', [SportsBotController::class, 'coverageSettings'])->name('coverage');
    Route::post('/coverage', [SportsBotController::class, 'saveCoverageSettings'])->name('coverage.save');
    Route::get('/scraper-settings', [SportsBotController::class, 'scraperSettings'])->name('scraper-settings');
    Route::post('/scraper-settings', [SportsBotController::class, 'saveScraperSettings'])->name('scraper-settings.save');
    Route::post('/telegram/send-diagnostics', [SportsBotController::class, 'sendTelegramDiagnostics'])->name('telegram.send-diagnostics');
    Route::post('/discord/send-diagnostics', [SportsBotController::class, 'sendDiscordDiagnostics'])->name('discord.send-diagnostics');
    Route::get('/discord/routes', [SportsBotController::class, 'discordRoutesIndex'])->name('discord.routes');
    Route::post('/discord/settings', [SportsBotController::class, 'saveDiscordSettings'])->name('discord.settings.save');
    Route::post('/discord/routes', [SportsBotController::class, 'saveDiscordRoute'])->name('discord.routes.save');
    Route::post('/discord/routes/test', [SportsBotController::class, 'testDiscordRoute'])->name('discord.routes.test');
    Route::delete('/discord/routes/{routeKey}', [SportsBotController::class, 'deleteDiscordRoute'])->name('discord.routes.delete');
    Route::get('/telegram/messages', [SportsBotController::class, 'telegramMessages'])->name('telegram.messages');
    Route::get('/telegram/topics', [SportsBotController::class, 'telegramTopics'])->name('telegram.topics');
    Route::post('/telegram/topics', [SportsBotController::class, 'saveTelegramTopic'])->name('telegram.topics.save');
    Route::post('/telegram/topics/sync', [SportsBotController::class, 'syncTelegramTopics'])->name('telegram.topics.sync');
    Route::post('/telegram/topics/import-legacy', [SportsBotController::class, 'importLegacyTelegramTopics'])->name('telegram.topics.import-legacy');
    Route::get('/telegram/routes', [SportsBotController::class, 'telegramRoutesIndex'])->name('telegram.routes');
    Route::post('/telegram/routes', [SportsBotController::class, 'saveTelegramRoute'])->name('telegram.routes.save');
    Route::delete('/telegram/routes/{routeKey}', [SportsBotController::class, 'deleteTelegramRoute'])->name('telegram.routes.delete');
    Route::get('/telegram/settings', [SportsBotController::class, 'telegramSettings'])->name('telegram.settings');
    Route::post('/telegram/settings', [SportsBotController::class, 'saveTelegramSettings'])->name('telegram.settings.save');
    Route::get('/telegram/webhook/diagnostics', [SportsBotController::class, 'telegramWebhookDiagnostics'])->name('telegram.webhook.diagnostics');
    Route::post('/telegram/webhook/set', [SportsBotController::class, 'setTelegramWebhook'])->name('telegram.webhook.set');
    Route::delete('/telegram/webhook', [SportsBotController::class, 'deleteTelegramWebhook'])->name('telegram.webhook.delete');
});
