<?php

declare(strict_types=1);

/*
 * Optional advanced config pattern:
 * keep runtime secrets in environment variables, then edit root config.php only
 * if you need to adjust polling, paths, or league aliases.
 */

return [
    'cron' => '*/2 * * * * /usr/bin/php /home/user/footballbot/check_live.php',
    'required_env' => [
        'TELEGRAM_BOT_TOKEN' => 'Telegram bot token from BotFather',
        'TELEGRAM_CHAT_ID' => 'Private group chat ID, usually starts with -100',
        'TELEGRAM_MESSAGE_THREAD_ID' => 'Optional Telegram forum topic ID for the default group',
        'THESPORTSDB_API_KEY' => 'TheSportsDB premium V2 API key',
        'BOT_TV_CHANNELS' => 'Optional TV channel slugs for pushed sports listings',
    ],
    'admin_exposed_env' => [
        'BOT_COVERAGE_PRESET',
        'BOT_ENABLED_SPORTS',
        'BOT_ENABLED_LEAGUE_IDS',
        'BOT_COVERAGE_COUNTRIES',
        'BOT_AUTO_ENABLE_DISCOVERED_LEAGUES',
        'BOT_MAX_SCHEDULE_LEAGUES',
        'TELEGRAM_UPDATES_ENABLED',
        'BOT_TELEGRAM_ROUTES_JSON',
        'BOT_ALLOWED_LEAGUE_IDS',
        'BOT_SEND_RED_CARDS',
        'BOT_SEND_YELLOW_CARDS',
        'BOT_SEND_SUBSTITUTIONS',
        'BOT_SEND_MATCH_PREVIEWS',
        'BOT_PREVIEW_HOURS_AHEAD',
        'BOT_CARD_BURSTS_ENABLED',
        'BOT_CARD_ROUTE_MODE',
        'BOT_CARD_TYPES_ENABLED',
        'BOT_CARD_BURST_MIN_FIXTURES',
        'BOT_CARD_BURST_MIN_LIVE',
        'BOT_CARD_BURST_MIN_RESULTS',
        'BOT_CARD_BURST_COOLDOWN_MINUTES',
        'BOT_CARD_MAX_PAGES_PER_RUN',
        'BOT_CARD_MAX_SENDS_PER_RUN',
        'BOT_CONTENT_PACKS_ENABLED',
        'BOT_CUSTOMER_GUIDE_ENABLED',
        'BOT_CUSTOMER_GUIDE_TIME',
        'BOT_CUSTOMER_GUIDE_LOOKAHEAD_HOURS',
        'BOT_TEAM_WATCHLIST',
        'BOT_PLAYER_WATCHLIST',
        'BOT_FOLLOW_BUTTONS_ENABLED',
        'BOT_MAX_FOLLOW_BUTTONS',
        'BOT_API_MIN_INTERVAL_MS',
        'BOT_LIVESCORE_CACHE_TTL',
        'BOT_TIMELINE_CACHE_TTL',
        'BOT_LOOKUP_CACHE_TTL',
        'BOT_MAX_LIVE_MATCHES_PER_RUN',
        'BOT_MAX_LIVE_MATCHES_PER_SPORT',
        'BOT_RENDER_ENGINE',
        'BOT_RENDER_CHROME_PATH',
        'BOT_RENDER_USER_DATA_DIR',
        'BOT_RENDER_EXTRA_ARGS',
        'BOT_SPORT_PROFILES_JSON',
        'BOT_HEALTH_ALERTS_ENABLED',
        'BOT_HEALTH_ALERT_TIME',
        'BOT_IMAGE_CLEANUP_SECONDS',
        'BOT_TV_ENABLED',
        'BOT_TV_SPORTS',
        'BOT_TV_DAILY_ALERTS',
        'BOT_TV_SEND_IMAGE',
    ],
    'allowed_leagues' => [
        '4328' => 'English Premier League',
        '4329' => 'EFL Championship',
        '4396' => 'League One',
        '4397' => 'League Two',
        '4482' => 'FA Cup',
        '4570' => 'EFL Cup',
    ],
    'tv_listing_example_channels' => [
        'sky_sports_main_event',
        'sky_sports_premier_league',
    ],
    'coverage_preset' => [
        'name' => 'uk_sports',
        'sports' => [
            'Soccer',
            'Rugby',
            'Rugby Union',
            'Rugby League',
            'Cricket',
            'Tennis',
            'Darts',
            'Snooker',
            'Golf',
            'Motorsport',
            'Formula 1',
            'Boxing',
            'MMA',
            'American Football',
            'Basketball',
            'Baseball',
            'Ice Hockey',
        ],
    ],
];
